version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bibliopy
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bibliopy
    ports:
      - "8000:8000"
    depends_on:
      - db